name: Deploy Website to S3

# Trigger this workflow on every push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your GitHub repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configure AWS credentials for CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3. Sync only website files to S3
      - name: Sync website files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "*.yml" \
            --exclude ".gitignore"

